#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo chmod 777 /etc/nginx/sites-available

sudo chmod 777 /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
