#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format,
# including all processes for all users, even those without a TTY, and showing process hierarchy.

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd
