#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and specific messages for certain iterations.

count=1
while [ $count -le 20 ]
do
    case $count in
        4)
            echo "$count and then bad luck from China"
            ;;
        9)
            echo "$count and then bad luck from Japan"
            ;;
        17)
            echo "$count and then bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    count=$((count + 1))
done
