#!/usr/bin/env bash
#Bash script that configures an Ubuntu server as follows:
#localhost resolves to 127.0.0.2
#facebook resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"

echo "$localhost_mapping"> ~/hosts.new
echo "$facebook_mapping">> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
